# 1.1 Traitement des données train_pol et train_claim

# Importation des modules

In [89]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# Importation de la base trainpol

In [90]:
Base = pd.read_csv("pg17trainpol.csv", delimiter=";", low_memory=False)

### Information sur la base

In [91]:
Base

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 31
0,A00072644,V01,A00072644-V01,Year 0,0.50,4,8.0,4.0,Monthly,No,...,Diesel,FIAT,STILO,10.0,7.0,192.0,Tourism,18000.0,1320,NaN
1,A00036953,V01,A00036953-V01,Year 0,0.50,4,11.0,1.0,Yearly,No,...,Diesel,PEUGEOT,RCZ,2.0,1.0,216.0,Tourism,32000.0,1399,NaN
2,A00079066,V01,A00079066-V01,Year 0,0.50,4,7.0,1.0,Yearly,No,...,Gasoline,NaN,SCENIC,8.0,6.0,185.0,Tourism,20800.0,1320,NaN
3,A00018024,V01,A00018024-V01,Year 0,0.64,3,5.0,1.0,Yearly,No,...,Gasoline,NaN,106,18.0,15.0,190.0,Tourism,12517.0,860,NaN
4,A00019276,V01,A00019276-V01,Year 0,0.72,1,1.0,1.0,Monthly,No,...,Gasoline,FORD,FIESTA,19.0,17.0,143.0,Tourism,9742.0,820,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100038,A00033699,V01,A00033699-V01,Year 0,0.50,3,11.0,2.0,Biannual,No,...,Diesel,NISSAN,TERRANO,9.0,3.0,155.0,Commercial,26800.0,1700,NaN
100039,A00012012,V01,A00012012-V01,Year 0,0.50,4,17.0,3.0,Yearly,No,...,Gasoline,AUDI,TT,12.0,6.0,243.0,Tourism,37710.0,1465,NaN
100040,A00073986,V01,A00073986-V01,Year 0,0.50,4,20.0,1.0,Biannual,Yes,...,Gasoline,FIAT,PUNTO,18.0,16.0,150.0,Tourism,9254.0,840,NaN
100041,A00053226,V01,A00053226-V01,Year 0,0.50,3,4.0,1.0,Biannual,No,...,Diesel,CITROEN,C3,9.0,9.0,180.0,Tourism,14250.0,1058,NaN
100042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.

In [92]:
Base.shape

(100043, 32)

La base de donnée contient 100 043 lignes (Observations) et 32 colonnes (Variables)

In [93]:
Base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100043 entries, 0 to 100042
Data columns (total 32 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_client         100042 non-null  object
 1   id_vehicle        100042 non-null  object
 2   id_policy         100042 non-null  object
 3   id_year           100042 non-null  object
 4   pol_bonus         100042 non-null  float64
 5   pol_coverage      100042 non-null  object
 6   pol_duration      100042 non-null  float64
 7   pol_sit_duration  100042 non-null  float64
 8   pol_pay_freq      100042 non-null  object
 9   pol_payd          100042 non-null  object
 10  pol_usage         100042 non-null  object
 11  pol_insee_code    100042 non-null  object
 12  drv_drv2          100042 non-null  object
 13  drv_age1          100042 non-null  float64
 14  drv_age2          100042 non-null  float64
 15  drv_sex1          99919 non-null   object
 16  drv_sex2          33186 non-null   object
 17  drv_age_lic1      100042 non-null  float64
 18  drv_age_lic2      100042 non-null  float64
 19  vh_age            100041 non-null  object
 20  vh_cyl            100042 non-null  float64
 21  vh_din            100042 non-null  float64
 22  vh_fuel           100023 non-null  object
 23  vh_make           87755 non-null   object
 24  vh_model          100042 non-null  object
 25  vh_sale_begin     100042 non-null  float64
 26  vh_sale_end       100042 non-null  float64
 27  vh_speed          100042 non-null  float64
 28  vh_type           100042 non-null  object
 29  vh_value          100042 non-null  float64
 30  vh_weight         100042 non-null  object
 31  Unnamed: 31       1 non-null       object
dtypes: float64(13), object(19)
memory usage: 24.4+ MB

### Copie de notre base

In [94]:
base = Base.copy()

### Gestion des doublons

Nous allons à cette étape utiliser la variable id_policy qui est le numéro d'identification de la police résultant de l'ajout de id_client et id_vehicle.

In [95]:
sum(base.duplicated('id_policy'))

42

In [96]:
sum(base.duplicated())

0

In [97]:
# len(base)-base.id_policy.nunique()

Elle nous permet de constater que notre base contient 42 doublons.

In [98]:
doublons = base[base.duplicated('id_policy', keep=False)].sort_values("id_policy")
doublons

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 31
6349,A00001830,V01,A00001830-V01,Year 0,0.50,4,14.0,3.0,Yearly,No,...,Diesel,CITROEN,C4 PICASSO,5.0,3.0,180.0,Tourism,27200.0,1539,NaN
40623,A00001830,V01,A00001830-V01,Year 0,0.50,4,14.0,3.0,Yearly,No,...,Diesel,CITROEN,C4 PICASSO,5.0,3.0,180.0,Tourism,27200.0,1539,NaN
44681,A00004437,V01,A00004437-V01,Year 0,0.50,4,19.0,6.0,Monthly,No,...,Diesel,FORD,FUSION,9.0,1.0,158.0,Tourism,14640.0,1102,NaN
30854,A00004437,V01,A00004437-V01,Year 0,0.50,4,19.0,6.0,Monthly,No,...,Diesel,FORD,FUSION,9.0,1.0,158.0,Tourism,14640.0,1102,NaN
97548,A00004689,V02,A00004689-V02,Year 0,0.68,4,1.0,1.0,Biannual,No,...,Diesel,RENAULT,SCENIC,6.0,5.0,190.0,Tourism,28350.0,1430,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72002,A00085938,V01,A00085938-V01,Year 0,0.58,4,8.0,5.0,Yearly,No,...,Gasoline,RENAULT,TWINGO,13.0,11.0,151.0,Tourism,8522.0,823,NaN
36639,A00088147,V01,A00088147-V01,Year 0,0.50,3,4.0,1.0,Yearly,No,...,Diesel,CITROEN,SAXO,15.0,8.0,158.0,Commercial,11362.0,890,NaN
89190,A00088147,V01,A00088147-V01,Year 0,0.50,3,4.0,1.0,Yearly,No,...,Diesel,CITROEN,SAXO,15.0,8.0,158.0,Commercial,11362.0,890,NaN
13712,A00088269,V01,A00088269-V01,Year 0,0.50,4,5.0,1.0,Yearly,No,...,Diesel,AUDI,A3,14.0,13.0,194.0,Tourism,22654.0,1170,NaN
47995,A00088269,V01,A00088269-V01,Year 0,0.50,4,5.0,1.0,Yearly,No,...,Diesel,AUDI,A3,14.0,13.0,194.0,Tourism,22654.0,1170,NaN

On constate qu'en suivant l'id_policy on a 42 doublons identiques pour chacunes de nos variables que l'on peut supprimer.
Nous allons supprimer la dernière occurrence car elle ne fait aucune différence avec la preemière pour chacunes de nos observations

In [99]:
base_ssDoub = base.drop_duplicates(subset='id_policy', keep='first')
base_ssDoub

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 31
0,A00072644,V01,A00072644-V01,Year 0,0.50,4,8.0,4.0,Monthly,No,...,Diesel,FIAT,STILO,10.0,7.0,192.0,Tourism,18000.0,1320,NaN
1,A00036953,V01,A00036953-V01,Year 0,0.50,4,11.0,1.0,Yearly,No,...,Diesel,PEUGEOT,RCZ,2.0,1.0,216.0,Tourism,32000.0,1399,NaN
2,A00079066,V01,A00079066-V01,Year 0,0.50,4,7.0,1.0,Yearly,No,...,Gasoline,NaN,SCENIC,8.0,6.0,185.0,Tourism,20800.0,1320,NaN
3,A00018024,V01,A00018024-V01,Year 0,0.64,3,5.0,1.0,Yearly,No,...,Gasoline,NaN,106,18.0,15.0,190.0,Tourism,12517.0,860,NaN
4,A00019276,V01,A00019276-V01,Year 0,0.72,1,1.0,1.0,Monthly,No,...,Gasoline,FORD,FIESTA,19.0,17.0,143.0,Tourism,9742.0,820,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100038,A00033699,V01,A00033699-V01,Year 0,0.50,3,11.0,2.0,Biannual,No,...,Diesel,NISSAN,TERRANO,9.0,3.0,155.0,Commercial,26800.0,1700,NaN
100039,A00012012,V01,A00012012-V01,Year 0,0.50,4,17.0,3.0,Yearly,No,...,Gasoline,AUDI,TT,12.0,6.0,243.0,Tourism,37710.0,1465,NaN
100040,A00073986,V01,A00073986-V01,Year 0,0.50,4,20.0,1.0,Biannual,Yes,...,Gasoline,FIAT,PUNTO,18.0,16.0,150.0,Tourism,9254.0,840,NaN
100041,A00053226,V01,A00053226-V01,Year 0,0.50,3,4.0,1.0,Biannual,No,...,Diesel,CITROEN,C3,9.0,9.0,180.0,Tourism,14250.0,1058,NaN
100042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.

In [100]:
base_ssDoub.shape

(100001, 32)

Notre nouvelle base sans doublons contient 100 001 lignes et 32 colonnes.

#### Verifions les doublons suivant l'id_client

In [101]:
sum(base_ssDoub.duplicated('id_client'))

8512

On constate que la base contient 8 512 doublons suivant l'id_client qui est le numéro d'identification du client.

In [102]:
doublons = base_ssDoub[base_ssDoub.duplicated('id_client', keep=False)].sort_values("id_client")
doublons

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 31
92790,A00000042,V03,A00000042-V03,Year 0,0.5,1,4.0,3.0,Yearly,No,...,Gasoline,SUZUKI,SJ 413,26.0,22.0,135.0,Commercial,12591.0,1330,NaN
99626,A00000042,V02,A00000042-V02,Year 0,0.5,1,4.0,3.0,1,No,...,Diesel,RENAULT,B70,25.0,21.0,112.0,Commercial,21552.0,0,NaN
34524,A00000042,V01,A00000042-V01,Year 0,0.5,1,4.0,3.0,Yearly,No,...,Diesel,AUDI,A6,11.0,7.0,219.0,Tourism,44380.0,1680,NaN
57174,A00000043,V02,A00000043-V02,Year 0,0.5,3,5.0,1.0,Monthly,No,...,Diesel,PEUGEOT,EXPERT,16.0,14.0,138.0,Commercial,17356.0,0,NaN
11926,A00000043,V01,A00000043-V01,Year 0,0.5,4,5.0,1.0,Monthly,No,...,Diesel,CITROEN,C4 PICASSO,4.0,3.0,180.0,Tourism,27000.0,1499,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53486,A00091439,V01,A00091439-V01,Year 0,0.5,3,7.0,1.0,Biannual,No,...,Diesel,PEUGEOT,206,9.0,6.0,180.0,Tourism,15950.0,1010,NaN
53353,A00091468,V02,A00091468-V02,Year 0,0.5,4,1.0,1.0,Yearly,No,...,Gasoline,NaN,CLIO,1.0,1.0,186.0,Tourism,19050.0,1190,NaN
61808,A00091468,V01,A00091468-V01,Year 0,0.5,4,7.0,3.0,Yearly,No,...,Diesel,NaN,ESPACE,5.0,4.0,190.0,Tourism,39350.0,1840,NaN
39106,A00091485,V01,A00091485-V01,Year 0,0.5,4,7.0,4.0,Biannual,No,...,Diesel,RENAULT,MASTER,15.0,13.0,130.0,Commercial,24269.0,0,NaN
87989,A00091485,V02,A00091485-V02,Year 0,0.5,4,4.0,2.0,Biannual,No,...,Gasoline,CITROEN,XANTIA,15.0,13.0,192.0,Tourism,18050.0,1234,NaN

Après analyse des doublons sur la base du numéro d'identification du client, on constate que les doublons ne sont pas forcémment les doublons car ils s'agit d'observations qui diffrèrent d'une variables à une autre suivant le même type du numéro d'identification du client.

### Gestion des données manquantes

### Dection des données manquantes

In [103]:
base_ssDoub.isna()

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 31
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
100039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
100040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
100041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
100042,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False

In [104]:
base_ssDoub.isna().sum()/len(base_ssDoub)*100

id_client            0.001000
id_vehicle           0.001000
id_policy            0.001000
id_year              0.001000
pol_bonus            0.001000
pol_coverage         0.001000
pol_duration         0.001000
pol_sit_duration     0.001000
pol_pay_freq         0.001000
pol_payd             0.001000
pol_usage            0.001000
pol_insee_code       0.001000
drv_drv2             0.001000
drv_age1             0.001000
drv_age2             0.001000
drv_sex1             0.123999
drv_sex2            66.839332
drv_age_lic1         0.001000
drv_age_lic2         0.001000
vh_age               0.002000
vh_cyl               0.001000
vh_din               0.001000
vh_fuel              0.020000
vh_make             12.284877
vh_model             0.001000
vh_sale_begin        0.001000
vh_sale_end          0.001000
vh_speed             0.001000
vh_type              0.001000
vh_value             0.001000
vh_weight            0.001000
Unnamed: 31         99.999000
dtype: float64

### Traitement des Valeurs manquantes

Dans une un premier temps je vais supprimer la dernière colonne  de ma base qui ne contient aucune informatio si ce n'est qu'un point au niveau de la 100 043ième observation

In [105]:
base_ssDoub = base_ssDoub.copy()

In [106]:
base_ssDoub.drop('Unnamed: 31', axis=1, inplace=True)

In [107]:
base_ssDoub

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_din,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight
0,A00072644,V01,A00072644-V01,Year 0,0.50,4,8.0,4.0,Monthly,No,...,116.0,Diesel,FIAT,STILO,10.0,7.0,192.0,Tourism,18000.0,1320
1,A00036953,V01,A00036953-V01,Year 0,0.50,4,11.0,1.0,Yearly,No,...,164.0,Diesel,PEUGEOT,RCZ,2.0,1.0,216.0,Tourism,32000.0,1399
2,A00079066,V01,A00079066-V01,Year 0,0.50,4,7.0,1.0,Yearly,No,...,113.0,Gasoline,NaN,SCENIC,8.0,6.0,185.0,Tourism,20800.0,1320
3,A00018024,V01,A00018024-V01,Year 0,0.64,3,5.0,1.0,Yearly,No,...,100.0,Gasoline,NaN,106,18.0,15.0,190.0,Tourism,12517.0,860
4,A00019276,V01,A00019276-V01,Year 0,0.72,1,1.0,1.0,Monthly,No,...,49.0,Gasoline,FORD,FIESTA,19.0,17.0,143.0,Tourism,9742.0,820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100038,A00033699,V01,A00033699-V01,Year 0,0.50,3,11.0,2.0,Biannual,No,...,125.0,Diesel,NISSAN,TERRANO,9.0,3.0,155.0,Commercial,26800.0,1700
100039,A00012012,V01,A00012012-V01,Year 0,0.50,4,17.0,3.0,Yearly,No,...,226.0,Gasoline,AUDI,TT,12.0,6.0,243.0,Tourism,37710.0,1465
100040,A00073986,V01,A00073986-V01,Year 0,0.50,4,20.0,1.0,Biannual,Yes,...,56.0,Gasoline,FIAT,PUNTO,18.0,16.0,150.0,Tourism,9254.0,840
100041,A00053226,V01,A00053226-V01,Year 0,0.50,3,4.0,1.0,Biannual,No,...,93.0,Diesel,CITROEN,C3,9.0,9.0,180.0,Tourism,14250.0,1058
100042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dans une un  temps je vais supprimer la dernière ligne de ma base qui ne contient aucune information aussi.

In [108]:
ligne_vide = base_ssDoub[base_ssDoub.isnull().all(axis=1)]
ligne_vide

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_din,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight
100042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
base_ssDoub = base_ssDoub[~base_ssDoub.isnull().all(axis=1)]

In [110]:
base_ssDoub

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_din,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight
0,A00072644,V01,A00072644-V01,Year 0,0.50,4,8.0,4.0,Monthly,No,...,116.0,Diesel,FIAT,STILO,10.0,7.0,192.0,Tourism,18000.0,1320
1,A00036953,V01,A00036953-V01,Year 0,0.50,4,11.0,1.0,Yearly,No,...,164.0,Diesel,PEUGEOT,RCZ,2.0,1.0,216.0,Tourism,32000.0,1399
2,A00079066,V01,A00079066-V01,Year 0,0.50,4,7.0,1.0,Yearly,No,...,113.0,Gasoline,NaN,SCENIC,8.0,6.0,185.0,Tourism,20800.0,1320
3,A00018024,V01,A00018024-V01,Year 0,0.64,3,5.0,1.0,Yearly,No,...,100.0,Gasoline,NaN,106,18.0,15.0,190.0,Tourism,12517.0,860
4,A00019276,V01,A00019276-V01,Year 0,0.72,1,1.0,1.0,Monthly,No,...,49.0,Gasoline,FORD,FIESTA,19.0,17.0,143.0,Tourism,9742.0,820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100037,A00016135,V01,A00016135-V01,Year 0,0.50,4,25.0,1.0,Yearly,No,...,143.0,Diesel,MERCEDES BENZ,C220,11.0,7.0,215.0,Tourism,33265.0,1545
100038,A00033699,V01,A00033699-V01,Year 0,0.50,3,11.0,2.0,Biannual,No,...,125.0,Diesel,NISSAN,TERRANO,9.0,3.0,155.0,Commercial,26800.0,1700
100039,A00012012,V01,A00012012-V01,Year 0,0.50,4,17.0,3.0,Yearly,No,...,226.0,Gasoline,AUDI,TT,12.0,6.0,243.0,Tourism,37710.0,1465
100040,A00073986,V01,A00073986-V01,Year 0,0.50,4,20.0,1.0,Biannual,Yes,...,56.0,Gasoline,FIAT,PUNTO,18.0,16.0,150.0,Tourism,9254.0,840
100041,A00053226,V01,A00053226-V01,Year 0,0.50,3,4.0,1.0,Biannual,No,...,93.0,Diesel,CITROEN,C3,9.0,9.0,180.0,Tourism,14250.0,1058

In [111]:
base_ssDoub = base_ssDoub.copy()

#### Vérifions notre base sans la dernière ligne et la dernière colonne

In [112]:
base_ssDoub.isna().sum()/len(base_ssDoub)*100

id_client            0.000
id_vehicle           0.000
id_policy            0.000
id_year              0.000
pol_bonus            0.000
pol_coverage         0.000
pol_duration         0.000
pol_sit_duration     0.000
pol_pay_freq         0.000
pol_payd             0.000
pol_usage            0.000
pol_insee_code       0.000
drv_drv2             0.000
drv_age1             0.000
drv_age2             0.000
drv_sex1             0.123
drv_sex2            66.839
drv_age_lic1         0.000
drv_age_lic2         0.000
vh_age               0.001
vh_cyl               0.000
vh_din               0.000
vh_fuel              0.019
vh_make             12.284
vh_model             0.000
vh_sale_begin        0.000
vh_sale_end          0.000
vh_speed             0.000
vh_type              0.000
vh_value             0.000
vh_weight            0.000
dtype: float64

On constate que : 
1) Les variables drv_sex1 et drv_sex2 qui désignent respectivement, pour chaque type de véhicule, le sexe des conducteurs masculins et feminins ayant des valeurs manquantes respectives de 0.123 % et 66.839 %. (ces valeurs manquantes ne sont pas à traiter)
2) La variable vh_age qui désigne l'âge du véhicule qui est la différence entre l'année de sortie et l'année en cours contient 0.001 % de valeurs manquantes.     
3) La variable vh_fuel qui désigne le type de carburant du véhicule avec principalement deux valeurs « Diesel » et « Essence » contient 0.019 % de valeurs manquantes.
4) La variable vh_make qui désigne le constructeur automobile qui dans le cas présents sont Renault, Peugeot et Citroën contient 12.284 % valeurs manquantes.

#### Traitement de la variable Age du véhicule

On a décidé d'utilisé la médian pour remplacer la valeur manquante

In [113]:
base_ssDoub.vh_age.value_counts(dropna=False)

vh_age
2      7668
1      6847
6      6408
3      6278
5      6132
       ...
58        1
65        1
_53       1
_40       1
60        1
Name: count, Length: 92, dtype: int64

On va essayer de supprimer le préfixe "_" au niveau des nombres et ensuite convertir la colonne en numérique

In [114]:
# Convertir la colonne 'vh_age' en type 'str'
base_ssDoub['vh_age'] = base_ssDoub['vh_age'].astype(str)

# Supprimer les underscores dans les modalités de la variable 'vh_age'
base_ssDoub['vh_age'] = base_ssDoub['vh_age'].str.replace('_', '')

# Transformer la variable 'vh_age' en numérique
base_ssDoub['vh_age'] = pd.to_numeric(base_ssDoub['vh_age'], errors='coerce')

On remplace la valeur manquante par la médiane

In [115]:
base_ssDoub['vh_age'] = base_ssDoub['vh_age'].fillna(base_ssDoub['vh_age'].median())

In [116]:
#verification
base_ssDoub.vh_age.value_counts(dropna=False)

vh_age
2.0     7675
1.0     6850
6.0     6413
3.0     6285
5.0     6135
        ...
66.0       1
64.0       1
58.0       1
65.0       1
60.0       1
Name: count, Length: 65, dtype: int64

#### Traitement de la variable pol_coverage

In [117]:
base_ssDoub.pol_coverage.value_counts(dropna=False)

pol_coverage
4    64491
3    17521
2     9338
1     8612
?       38
Name: count, dtype: int64

In [118]:
modCat = base_ssDoub[base_ssDoub.pol_coverage != '?'].pol_coverage.value_counts(normalize=True) # présentation des modalités sans la modalité "?"
modCat

pol_coverage
4    0.645155
3    0.175277
2    0.093415
1    0.086153
Name: proportion, dtype: float64

In [119]:
modCat.values

array([0.64515516, 0.17527661, 0.0934155 , 0.08615274])

In [120]:
# Nous allons réalisé un tirage aléatoire (pondérée) à l'aide de Numphy
np.random.seed(42)
np.random.choice(modCat.index, size=1, p = modCat.values)[0]

'4'

Il ressort que le modalité "?" a plus de chances d'appartenir à la modalité "4" alors dans la prochaine étape nous allons attribuer les 29 observations de la modalité "?" à la modalité "4".

In [121]:
base_ssDoub.pol_coverage = base_ssDoub.pol_coverage.apply(lambda x: 
                   np.random.choice(modCat.index, size=1, 
                                    p = modCat.values)[0] if x == '?' else x)

In [122]:
# On peut verifier que les 19 observations de la modalité "?" ont été attribué à la modalité "4"
# base_ssDoub.pol_coverage.value_counts(dropna=False)

#### Traitement de la variable pol_pay_freq

In [123]:
base_ssDoub.pol_pay_freq.value_counts(dropna=False)

pol_pay_freq
Yearly       35218
Monthly      29933
Biannual     29606
1             2515
Quarterly     2397
4              150
6               96
12              85
Name: count, dtype: int64

Dans le cas présent je vais repartir les modalités en chiffres selon les hypoithèses suivantes : 
- 1 pourrait représenter un paiement unique (équivalent à "Yearly").
- 4 pourrait représenter une fréquence trimestrielle (équivalent à "Quarterly").
- 6 pourrait représenter une fréquence semestrielle (équivalent à "Biannual").
- 12 pourrait représenter une fréquence mensuelle (équivalent à "Monthly").


La méthode va consister à replace chaque chiffre par son équivalent

In [124]:
# Créer une copie explicite pour éviter SettingWithCopyWarning
base_ssDoub = base_ssDoub.copy()

# Remplacer les modalités de la variable 'pol_pay_freq'
base_ssDoub['pol_pay_freq'] = base_ssDoub['pol_pay_freq'].replace({'1': 'Yearly', '4': 'Quarterly', '6': 'Biannual', '12': 'Monthly'})

In [125]:
# verification
base_ssDoub.pol_pay_freq.value_counts(dropna=False)

pol_pay_freq
Yearly       37733
Monthly      30018
Biannual     29702
Quarterly     2547
Name: count, dtype: int64

#### Traitement de la variable drv_sex1

In [126]:
base_ssDoub.drv_sex1.value_counts(dropna=False)

drv_sex1
M      60155
F      39722
NaN      123
Name: count, dtype: int64

In [127]:
base_ssDoub = base_ssDoub.copy()

Nous allons filter la base pour voir la cohérence des varibles drv_drv2, drv_sex1, drv_sex2, drv_age1, drv_age2, drv_age_lic1 et drv_age_lic2

In [128]:
# Filtrer les lignes où drv_drv2 est 'Yes'
filtered_df = base_ssDoub[base_ssDoub['drv_drv2'] == 'Yes']

# Filtrer les lignes où drv_sex1 est NaN, drv_sex2 est 'M' ou 'F', et drv_age1, drv_age2, drv_age_lic1 et drv_age_lic2 ont des valeurs
result_df = filtered_df[
    (filtered_df['drv_sex1'].isna()) &
    (filtered_df['drv_sex2'].isin(['M', 'F'])) &
    (filtered_df['drv_age1'].notnull()) &
    (filtered_df['drv_age2'].notnull()) &
    (filtered_df['drv_age_lic1'].notnull()) &
    (filtered_df['drv_age_lic2'].notnull())
]

# Afficher le résultat
result_df

,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,...,vh_din,vh_fuel,vh_make,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight
86,A00005440,V01,A00005440-V01,Year 0,0.50,4,27.0,7.0,Yearly,No,...,120.0,Diesel,RENAULT,SCENIC,8.0,6.0,188.0,Tourism,24150.0,1430
152,A00007657,V01,A00007657-V01,Year 0,0.50,4,15.0,1.0,Monthly,No,...,55.0,Gasoline,FIAT,PANDA,8.0,5.0,150.0,Tourism,9145.0,840
891,A00039087,V01,A00039087-V01,Year 0,0.50,3,8.0,1.0,Yearly,No,...,113.0,Diesel,NaN,ESPACE,13.0,11.0,178.0,Tourism,33463.0,1690
1549,A00031770,V01,A00031770-V01,Year 0,0.68,4,3.0,1.0,Monthly,No,...,109.0,Diesel,CITROEN,C4 PICASSO,4.0,3.0,180.0,Tourism,26200.0,1499
2114,A00085193,V01,A00085193-V01,Year 0,0.50,4,2.0,2.0,Yearly,No,...,140.0,Diesel,AUDI,A3,7.0,5.0,207.0,Tourism,30780.0,1410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97649,A00088085,V01,A00088085-V01,Year 0,0.50,2,1.0,1.0,Biannual,No,...,45.0,Gasoline,CITROEN,AX,25.0,18.0,145.0,Tourism,8157.0,640
97923,A00056519,V01,A00056519-V01,Year 0,0.50,4,5.0,2.0,Yearly,No,...,191.0,Diesel,MERCEDES BENZ,ML280,6.0,2.0,200.0,Tourism,54150.0,2110
98066,A00081191,V01,A00081191-V01,Year 0,0.50,4,10.0,2.0,Monthly,No,...,125.0,Diesel,OPEL,ZAFIRA,9.0,7.0,187.0,Tourism,23930.0,1300
99480,A00012029,V01,A00012029-V01,Year 0,0.50,4,24.0,6.0,Biannual,No,...,96.0,Gasoline,RENAULT,MEGANE,12.0,11.0,185.0,Tourism,15535.0,1080
99890,A00049852,V01,A00049852-V01,Year 0,0.50,4,3.0,3.0,Yearly,No,...,150.0,Diesel,TOYOTA,AVENSIS,6.0,3.0,210.0,Tourism,25700.0,1455

On constate qu'il y a environ 123 valeurs manquantes qui respectent les conditions du filtre ce qui nous rassure que nos valeurs manquantes de la variable drv_sex1 doivent être trouver

Nous allons utilisé la méthode de proportions pour repartir les 123 valeurs manquantes de la variable drv_sex1

In [129]:
# Calculer les proportions
proportions = base_ssDoub['drv_sex1'].value_counts(normalize=True)
proportions = proportions.dropna()  # Exclure les NaN

In [130]:
# Remplir les NaN aléatoirement en fonction des proportions
base_ssDoub['drv_sex1'] = base_ssDoub['drv_sex1'].apply(
    lambda x: np.random.choice(proportions.index, p=proportions.values) if pd.isna(x) else x
)

Nous allons renommé les variales "M" en Male et "F" en Female

In [131]:
base_ssDoub['drv_sex1'] = base_ssDoub['drv_sex1'].replace({'M': 'Male', 'F': 'Female'})

In [132]:
# vérification
base_ssDoub.drv_sex1.value_counts(dropna=False)

drv_sex1
Male      60231
Female    39769
Name: count, dtype: int64

#### Traitement de la variable drv_sex2

In [133]:
base_ssDoub.drv_sex2.value_counts(dropna=False)

drv_sex2
NaN    66839
F      20317
M      12844
Name: count, dtype: int64

Nous allons renommé les variales "M" en Male et "F" en Female

In [134]:
base_ssDoub['drv_sex2'] = base_ssDoub['drv_sex2'].replace({'M': 'Male', 'F': 'Female'})

In [135]:
# vérification
base_ssDoub.drv_sex2.value_counts(dropna=False)

drv_sex2
NaN       66839
Female    20317
Male      12844
Name: count, dtype: int64

#### Traitement de la variable vh_fuel

In [136]:
base_ssDoub.vh_fuel.value_counts(dropna=False)

vh_fuel
Diesel      54872
Gasoline    44996
Hybrid         61
Gazol          52
NaN            19
Name: count, dtype: int64

Au regard du nombre de valeurs manquantes assez faible, nous avons décider d'amputer par le mode, vu qu'il s'agit d'une variable qualitative.

In [137]:
base_ssDoub.vh_fuel.mode()[0]

'Diesel'

In [138]:
base_ssDoub['vh_fuel'] = base_ssDoub['vh_fuel'].fillna(base_ssDoub['vh_fuel'].mode()[0])

In [139]:
# vérification
base_ssDoub.vh_fuel.value_counts(dropna=False)

vh_fuel
Diesel      54891
Gasoline    44996
Hybrid         61
Gazol          52
Name: count, dtype: int64

#### Traitement de la variable vh_make

In [140]:
base_ssDoub.vh_make.value_counts(dropna=False)

vh_make
RENAULT     19772
PEUGEOT     16853
CITROEN     15794
NaN         12284
FORD         4487
            ...
INFINITI        1
ASIA            1
APAL            1
LM SOVRA        1
HUMMER          1
Name: count, Length: 102, dtype: int64

Nous allons utiliser une répartition proportionnelle c'est à dire remplir de facon aléatoire les valeurs manquantes en respectant la répartition existante des catégories de chaque fabriquant de véhicule.

In [141]:
# Calculer les proportions
proportions = base_ssDoub['vh_make'].value_counts(normalize=True)
proportions = proportions.dropna()  # Exclure les NaN

In [142]:
# Remplir les NaN aléatoirement en fonction des proportions
base_ssDoub['vh_make'] = base_ssDoub['vh_make'].apply(
    lambda x: np.random.choice(proportions.index, p=proportions.values) if pd.isna(x) else x
)

In [143]:
# Vérification
base_ssDoub.vh_make.value_counts(dropna=False)

vh_make
RENAULT     22559
PEUGEOT     19252
CITROEN     18037
FORD         5112
OPEL         4109
            ...
BENTLEY         1
LM SOVRA        1
APAL            1
ASIA            1
HUMMER          1
Name: count, Length: 101, dtype: int64

In [144]:
base_ok = base_ssDoub.copy()

#### Traitement de la variable vh_value

In [145]:
# Compter le nombre de véhicules dont la valeur est égale à 0
vehicules_valeur_zero = base_ok[base_ok['vh_value'] == 0].shape[0]
# Afficher le nombre de véhicules
print("Nous avons", vehicules_valeur_zero, "véhicules de valeur 0")

Nous avons 2 véhicules de valeur 0

Nous allons supprimer les vehicules dont la valeur est nulle

In [146]:
# Supprimer les véhicules dont la valeur est égale à 0
base_ok = base_ok[base_ok['vh_value']!=0]

#### Traitement de la variable vh_weight

In [147]:
base_ok.vh_weight.value_counts(dropna=False)

vh_weight
0        3743
950      1900
1320     1726
890      1491
790      1428
         ...
1,138       1
1,61        1
1,75        1
2265        1
1,399       1
Name: count, Length: 1347, dtype: int64

D'abord, nous allons supprimer la virgule "," des différentes modalités de notre variable

In [148]:
# Supprimer les virgules dans les modalités de la variable 'vh_weight'
base_ok['vh_weight'] = base_ok['vh_weight'].str.replace(',','')

In [149]:
# Transformer la variable 'vh_weight' en numérique
base_ok['vh_weight'] = pd.to_numeric(base_ok['vh_weight'])

Nous allons nous intérréser aux vehicules dont le poids est supérieur à 500Kg car de nos recherches le poids moyen du plus petit vehicule est de 500

In [150]:
Base_0 = base_ok[(base_ok['vh_weight']>400) & (base_ok['vh_weight']<4000)]

In [151]:
Base_0.vh_weight.describe()

count    95770.000000
mean      1172.446476
std        288.341711
min        500.000000
25%        960.000000
50%       1145.000000
75%       1320.000000
max       3500.000000
Name: vh_weight, dtype: float64

Nous allons traiter l'age < 18 pour la variable drv_age2

In [152]:
# Compter le nombre de conducteurs 2 dont la valeur de l'age est inf à 18 ANS
age_min = Base_0[Base_0['drv_age2'] < 18].shape[0]
# Afficher le nombre
print("Nous avons", age_min, "conducteurs qui ont moins de 18 ANS")

Nous avons 63320 conducteurs qui ont moins de 18 ANS

On retient l'age supérieur à 18 ans pour les conducteurs selon la consigne

In [153]:
trainpol = Base_0[Base_0['drv_age2']>18]

In [154]:
trainpol.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32313 entries, 1 to 100037
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_client         32313 non-null  object
 1   id_vehicle        32313 non-null  object
 2   id_policy         32313 non-null  object
 3   id_year           32313 non-null  object
 4   pol_bonus         32313 non-null  float64
 5   pol_coverage      32313 non-null  object
 6   pol_duration      32313 non-null  float64
 7   pol_sit_duration  32313 non-null  float64
 8   pol_pay_freq      32313 non-null  object
 9   pol_payd          32313 non-null  object
 10  pol_usage         32313 non-null  object
 11  pol_insee_code    32313 non-null  object
 12  drv_drv2          32313 non-null  object
 13  drv_age1          32313 non-null  float64
 14  drv_age2          32313 non-null  float64
 15  drv_sex1          32313 non-null  object
 16  drv_sex2          32313 non-null  object
 17  drv_age_lic1      32313 non-null  float64
 18  drv_age_lic2      32313 non-null  float64
 19  vh_age            32313 non-null  float64
 20  vh_cyl            32313 non-null  float64
 21  vh_din            32313 non-null  float64
 22  vh_fuel           32313 non-null  object
 23  vh_make           32313 non-null  object
 24  vh_model          32313 non-null  object
 25  vh_sale_begin     32313 non-null  float64
 26  vh_sale_end       32313 non-null  float64
 27  vh_speed          32313 non-null  float64
 28  vh_type           32313 non-null  object
 29  vh_value          32313 non-null  float64
 30  vh_weight         32313 non-null  int64
dtypes: float64(14), int64(1), object(16)
memory usage: 7.9+ MB

In [155]:
trainpol.shape # la nouvelle dimension de la base

(32313, 31)

In [156]:
trainpol.to_csv("trainpol_propre.csv")

# Importation base trainclaim

In [157]:
#Importons notre base nommée pg17trainclaim.csv
pg=pd.read_csv("pg17trainclaim.csv",sep= ";", decimal=".")
# affichons la structure de la base
pg.head()

   id_client id_vehicle id_year id_claim  claim_nb     claim_amount
0  A00047578        V01  Year 0     CL01         1     amount= 1236
1  A00058432        V01  Year 0     CL01         1    amount= 59.84
2  A00047550        V01  Year 0     CL02         1  amount= 2683.76
3  A00012792        V01  Year 0     CL01         1    amount= 84.05
4  A00032112        V01  Year 0     CL01         1   amount= 104.49

### Gestion des doublons de la base trainclaim

In [158]:
len(pg)

14545

In [159]:
#pour voir directement combien de valeur en double
len(pg)-pg.id_client.nunique()
# la difference entre le nombre d'observation et le nombre de valeur sans doublons
#Il y a 1716 Doublons

1716

In [160]:
#pour compter les doublon pur/parfaits
sum(pg.duplicated()) # Doublons purs

0

In [161]:
sum(pg.duplicated('id_client'))

1716

In [162]:
# Identifier les lignes dupliquées
duplicated = pg[pg.duplicated('id_client', keep=False)]
# Trier les lignes dupliquées par ordre croissant de 'id_client'
duplicated = duplicated.sort_values(by='id_client')
# Afficher les lignes dupliquées triées
duplicated

       id_client id_vehicle id_year id_claim  claim_nb     claim_amount
3790   A00000103        V01  Year 0     CL02         1   amount= 419.63
292    A00000103        V01  Year 0     CL01         1  amount= 1389.39
8380   A00000210        V01  Year 0     CL02         1    amount= 588.5
7704   A00000210        V01  Year 0     CL01         1   amount= 231.31
3931   A00000221        V01  Year 0     CL01         1   amount= 671.47
...          ...        ...     ...      ...       ...              ...
10849  A00091466        V01  Year 0     CL01         1   amount= 856.64
8889   A00105274        V01  Year 0     CL02         1  amount= 2683.76
6445   A00105274        V01  Year 0     CL01         1  amount= 1146.34
1056   A00116003        V01  Year 0     CL01         1  amount= 5087.17
6009   A00116003        V01  Year 0     CL02         1  amount= 1679.65

[3227 rows x 6 columns]

On constate que l'identifant claimb change pour certains clients ayant le même identifiant et le même identifaint de vehicule, on ne peut donc pas les supprimer.

In [163]:
# Supprimer le préfixe "amount= " de la variable claim_amount
pg['claim_amount'] = pg['claim_amount'].str.replace('amount= ', '')
# Convertir la colonne claim_amount en numérique
pg['claim_amount'] = pd.to_numeric(pg['claim_amount'], errors='coerce')
# Afficher les premières lignes pour vérifier le résultat
pg.head()

   id_client id_vehicle id_year id_claim  claim_nb  claim_amount
0  A00047578        V01  Year 0     CL01         1       1236.00
1  A00058432        V01  Year 0     CL01         1         59.84
2  A00047550        V01  Year 0     CL02         1       2683.76
3  A00012792        V01  Year 0     CL01         1         84.05
4  A00032112        V01  Year 0     CL01         1        104.49

In [164]:
pg[pg['id_client'].duplicated()].sort_values(by='id_client').head(50)

       id_client id_vehicle id_year id_claim  claim_nb  claim_amount
3790   A00000103        V01  Year 0     CL02         1        419.63
8380   A00000210        V01  Year 0     CL02         1        588.50
8832   A00000221        V01  Year 0     CL02         1        755.66
12741  A00000241        V01  Year 0     CL01         1       1040.74
10214  A00000241        V01  Year 0     CL03         1        138.28
10227  A00000241        V01  Year 0     CL02         1       3481.36
13991  A00000271        V01  Year 0     CL02         1       4916.24
6822   A00000299        V02  Year 0     CL01         1         11.54
13058  A00000351        V01  Year 0     CL03         1        672.89
11478  A00000351        V01  Year 0     CL02         1        558.68
7528   A00000389        V01  Year 0     CL02         1        450.04
13000  A00000464        V01  Year 0     CL01         1       -766.25
14226  A00000655        V01  Year 0     CL01         1       1010.41
7882   A00000696        V01  Year 0     CL01         1       1236.00
9012   A00000795        V02  Year 0     CL01         1        618.00
10307  A00000871        V01  Year 0     CL01         1        360.19
822    A00000874        V01  Year 0     CL03         1        142.56
9451   A00000874        V01  Year 0     CL02         1       1010.41
5027   A00000990        V01  Year 0     CL01         1        319.31
8952   A00001134        V01  Year 0     CL02         1        612.46
9057   A00001153        V02  Year 0     CL01         1       1236.00
10926  A00001276        V01  Year 0     CL01         1       1236.00
14498  A00001318        V01  Year 0     CL01         1        -34.72
6648   A00001326        V01  Year 0     CL02         1       1132.37
4153   A00001326        V01  Year 0     CL03         1       1758.31
10244  A00001369        V01  Year 0     CL02         1        310.18
7548   A00001444        V01  Year 0     CL02         1       1236.00
12689  A00001654        V01  Year 0     CL01         1        395.18
5078   A00002123        V03  Year 0     CL01         1        994.10
12112  A00002154        V01  Year 0     CL02         1       1236.00
7241   A00002183        V01  Year 0     CL03         1        346.81
8429   A00002183        V01  Year 0     CL01         1       -173.96
5055   A00002197        V01  Year 0     CL01         1       4198.22
1998   A00002197        V01  Year 0     CL02         1         75.72
5470   A00002265        V01  Year 0     CL01         1         86.95
13519  A00002265        V01  Year 0     CL03         1        916.15
1198   A00002297        V01  Year 0     CL01         1        901.59
8098   A00002516        V01  Year 0     CL01         1        768.66
8665   A00002546        V02  Year 0     CL01         1        825.73
11083  A00002566        V01  Year 0     CL01         1        512.80
14307  A00002590        V01  Year 0     CL01         1       -193.86
4506   A00002601        V01  Year 0     CL02         1       1533.46
2354   A00002651        V02  Year 0     CL02         1        631.27
2417   A00002651        V02  Year 0     CL01         1       1236.00
13030  A00002708        V01  Year 0     CL01         1       1010.41
11243  A00002726        V01  Year 0     CL01         1        498.85
2642   A00002726        V02  Year 0     CL02         1        130.11
12718  A00002790        V01  Year 0     CL02         1         28.50
7645   A00002950        V01  Year 0     CL02         1       -583.45
14190  A00002956        V01  Year 0     CL02         1       2453.28

In [165]:
other_columns = [col for col in pg.columns if col not in ['id_client', 'id_vehicle','claim_amount', 'claim_nb']] 
df_sin = pg[['id_client', 'id_vehicle','claim_amount', 'claim_nb']]
aggsin = df_sin.groupby(['id_client','id_vehicle']).agg(
    nb_sin=pd.NamedAgg(column='claim_nb', aggfunc='sum'),  # Compter le nombre de sinistre par client
    remb_total=pd.NamedAgg(column='claim_amount', aggfunc='sum'),  # Somme des montants des réclamations par client
).reset_index()

aggsin.head(10)

   id_client id_vehicle  nb_sin  remb_total
0  A00000009        V01       1      927.16
1  A00000016        V01       1      555.48
2  A00000026        V01       1      478.01
3  A00000040        V01       1      512.83
4  A00000056        V01       1     1236.00
5  A00000070        V01       1      158.28
6  A00000072        V01       1     -477.91
7  A00000076        V01       1     -991.69
8  A00000092        V01       1     1429.82
9  A00000103        V01       2     1809.02

In [166]:
#pg.to_excel("pg.xlsx", sheet_name="base_pg", index=False)

In [167]:
pg_claim = pg.copy()

In [168]:
pg_claim.to_csv("trainclaim_propre.csv")