# 1.3 Création des bases assurés et sinistrés

In [6]:
import numpy as np, pandas as pd

In [ ]:
base_ass_trainpol = pd.read_csv("trainpol_propre.csv", sep=',')
base_ass_trainclaim = pd.read_csv("trainclaim_propre.csv", sep=',')
#base_ass_baseclimat = pd.read_csv("baseclimat_propre.csv", dec=',')

### Création de la base des assurés

Nous allons utiliser la fusion en utilisant left pour faire apparaitre dans notre base de données définitive les assuré sinitré comme ceux non sinistrés.

In [ ]:
base_ass = pd.merge(base_ass_trainpol, base_ass_trainclaim, on = ['id_client', 'id_vehicle'],how = 'left')
base_ass.head()

,Unnamed: 0_x,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,...,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 0_y,nb_sin,claim_amount
0,1,A00036953,V01,A00036953-V01,Year 0,0.50,4,11.0,1.0,Yearly,...,RCZ,2.0,1.0,216.0,Tourism,32000.0,1399,NaN,NaN,NaN
1,3,A00018024,V01,A00018024-V01,Year 0,0.64,3,5.0,1.0,Yearly,...,106,18.0,15.0,190.0,Tourism,12517.0,860,NaN,NaN,NaN
2,6,A00071159,V01,A00071159-V01,Year 0,0.50,4,9.0,1.0,Biannual,...,407,7.0,6.0,208.0,Tourism,29200.0,1580,NaN,NaN,NaN
3,9,A00063340,V01,A00063340-V01,Year 0,0.50,4,2.0,2.0,Yearly,...,ESPACE,9.0,5.0,188.0,Tourism,38850.0,1782,NaN,NaN,NaN
4,14,A00011762,V01,A00011762-V01,Year 0,0.50,4,10.0,6.0,Biannual,...,GOLF,11.0,6.0,195.0,Tourism,21435.0,1260,NaN,NaN,NaN

### Création de la base des assurés sinistrés

Cette fusion va nous permettre d'obtenir une base donnée qui contient que les assurés qui ont eu un sinistre

In [ ]:
Base_sin = pd.merge(base_ass_trainpol, base_ass_trainclaim, on = ['id_client', 'id_vehicle'],how = 'inner')
Base_sin.head()

,Unnamed: 0_x,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,...,vh_model,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 0_y,nb_sin,claim_amount
0,37,A00031330,V01,A00031330-V01,Year 0,0.50,3,30.0,1.0,Yearly,...,206,13.0,8.0,170.0,Tourism,11950.0,950,4332,1,-338.76
1,56,A00056658,V01,A00056658-V01,Year 0,0.50,4,13.0,1.0,Biannual,...,SCENIC,2.0,1.0,180.0,Tourism,23100.0,1385,7855,1,0.00
2,62,A00004603,V02,A00004603-V02,Year 0,0.50,4,12.0,1.0,Quarterly,...,C4 PICASSO,2.0,1.0,195.0,Tourism,29200.0,1581,648,1,130.11
3,68,A00034712,V01,A00034712-V01,Year 0,0.62,2,4.0,2.0,Monthly,...,300,26.0,23.0,190.0,Tourism,30295.0,1370,4796,1,230.72
4,77,A00081062,V02,A00081062-V02,Year 0,0.50,3,19.0,4.0,Yearly,...,R19,19.0,17.0,161.0,Tourism,14788.0,1005,11233,1,1236.00

In [48]:
print("Les dimensions de notre base des assurés et des non assurés est :",base_ass.shape)

Les dimensions de notre base des assurés et des non assurés est : (32313, 35)

In [50]:
print("Les dimensions de notre base des sinistrés uniquement est :",Base_sin.shape)

Les dimensions de notre base des sinistrés uniquement est : (4386, 35)

Nous allons essayer de de calculer la frequence d'exposition de au sinistre dans notre base de donnée de sinistre pour ce faire, nous allons considérer que l'exposition pour une année de l'ensemble de nos assurés est de 1 ensuite considérer que les individus qui n'ont eu aucun sinistre dans la base de données Base_1 sont ceux qui sont NaN au niveau de variable nb_sin.

In [66]:
base_ass["id_year"] = base_ass["id_year"].replace("Year 0", 1)

In [67]:
base_ass["nb_sin"] = base_ass["nb_sin"].replace(np.nan, 0)

In [68]:
base_ass["claim_amount"] = base_ass["claim_amount"].replace(np.nan, 0)

Déterminons la fréquence d'être sinistré au sein de notre base de donnée.

In [70]:
freq = sum(base_ass.nb_sin)/sum(base_ass.id_year)
freq

0.15374617027202675

In [22]:
base_ass.claim_amount.value_counts(dropna=False)

claim_amount
0.00       28146
1236.00      258
106.14       109
1010.41       92
110.98        44
           ...
792.19         1
100.36         1
539.21         1
2472.96        1
5013.73        1
Name: count, Length: 3829, dtype: int64

### Traitement de la base définitive

In [23]:
base_ass.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32895 entries, 0 to 32894
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0_x      32895 non-null  int64
 1   id_client         32895 non-null  object
 2   id_vehicle        32895 non-null  object
 3   id_policy         32895 non-null  object
 4   id_year           32895 non-null  int64
 5   pol_bonus         32895 non-null  float64
 6   pol_coverage      32895 non-null  int64
 7   pol_duration      32895 non-null  float64
 8   pol_sit_duration  32895 non-null  float64
 9   pol_pay_freq      32895 non-null  object
 10  pol_payd          32895 non-null  object
 11  pol_usage         32895 non-null  object
 12  pol_insee_code    32895 non-null  object
 13  drv_drv2          32895 non-null  object
 14  drv_age1          32895 non-null  float64
 15  drv_age2          32895 non-null  float64
 16  drv_sex1          32895 non-null  object
 17  drv_sex2          32895 non-null  object
 18  drv_age_lic1      32895 non-null  float64
 19  drv_age_lic2      32895 non-null  float64
 20  vh_age            32895 non-null  float64
 21  vh_cyl            32895 non-null  float64
 22  vh_din            32895 non-null  float64
 23  vh_fuel           32895 non-null  object
 24  vh_make           32895 non-null  object
 25  vh_model          32895 non-null  object
 26  vh_sale_begin     32895 non-null  float64
 27  vh_sale_end       32895 non-null  float64
 28  vh_speed          32895 non-null  float64
 29  vh_type           32895 non-null  object
 30  vh_value          32895 non-null  float64
 31  vh_weight         32895 non-null  int64
 32  Unnamed: 0_y      4968 non-null   float64
 33  id_claim          4968 non-null   object
 34  claim_nb          32895 non-null  float64
 35  claim_amount      32895 non-null  float64
dtypes: float64(17), int64(4), object(15)
memory usage: 9.0+ MB

In [24]:
Base_sin.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4749 entries, 0 to 4967
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0_x      4749 non-null   int64
 1   id_client         4749 non-null   object
 2   id_vehicle        4749 non-null   object
 3   id_policy         4749 non-null   object
 4   id_year           4749 non-null   object
 5   pol_bonus         4749 non-null   float64
 6   pol_coverage      4749 non-null   int64
 7   pol_duration      4749 non-null   float64
 8   pol_sit_duration  4749 non-null   float64
 9   pol_pay_freq      4749 non-null   object
 10  pol_payd          4749 non-null   object
 11  pol_usage         4749 non-null   object
 12  pol_insee_code    4749 non-null   object
 13  drv_drv2          4749 non-null   object
 14  drv_age1          4749 non-null   float64
 15  drv_age2          4749 non-null   float64
 16  drv_sex1          4749 non-null   object
 17  drv_sex2          4749 non-null   object
 18  drv_age_lic1      4749 non-null   float64
 19  drv_age_lic2      4749 non-null   float64
 20  vh_age            4749 non-null   float64
 21  vh_cyl            4749 non-null   float64
 22  vh_din            4749 non-null   float64
 23  vh_fuel           4749 non-null   object
 24  vh_make           4749 non-null   object
 25  vh_model          4749 non-null   object
 26  vh_sale_begin     4749 non-null   float64
 27  vh_sale_end       4749 non-null   float64
 28  vh_speed          4749 non-null   float64
 29  vh_type           4749 non-null   object
 30  vh_value          4749 non-null   float64
 31  vh_weight         4749 non-null   int64
 32  Unnamed: 0_y      4749 non-null   int64
 33  id_claim          4749 non-null   object
 34  claim_nb          4749 non-null   int64
 35  claim_amount      4749 non-null   float64
dtypes: float64(15), int64(5), object(16)
memory usage: 1.3+ MB

In [ ]:
base_ass = base_ass.copy()

In [ ]:
print("La nouvelle dimension de notre base définitive est :",base_ass.shape)

La nouvelle dimension de notre base définitive est : (32895, 36)

In [ ]:
len(base_ass)

32895

### Gestion des doublons de la base définitive

In [ ]:
#pour voir directement combien d'observation on a en double
print("La base contient", len(base_ass)-base_ass.id_client.nunique(), "doublons") # la difference entre le nombre d'observation total et le nombre d'observation sans doublons

La base contient 2621 doublons

In [ ]:
#pour compter les doublon pur/parfaits
print("La base contient",sum(base_ass.duplicated()),"Doublons purs")

La base contient 0 Doublons purs

In [ ]:
# Affichons les doubons impurs
doublons_base_ass = base_ass[base_ass.duplicated('id_client', keep=False)].sort_values("id_client")
doublons_base_ass

,Unnamed: 0_x,id_client,id_vehicle,id_policy,id_year,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,...,vh_sale_begin,vh_sale_end,vh_speed,vh_type,vh_value,vh_weight,Unnamed: 0_y,id_claim,claim_nb,claim_amount
21548,65816,A00000052,V01,A00000052-V01,1,0.54,1,5.0,2.0,Yearly,...,28.0,18.0,155.0,Tourism,12867.0,880,NaN,NaN,0.0,0.00
14786,45136,A00000052,V02,A00000052-V02,1,0.54,4,2.0,2.0,Yearly,...,11.0,10.0,219.0,Tourism,37046.0,1575,NaN,NaN,0.0,0.00
12660,38612,A00000103,V01,A00000103-V01,1,0.50,4,1.0,1.0,Yearly,...,4.0,1.0,182.0,Tourism,37330.0,1604,3790.0,CL02,1.0,419.63
12659,38612,A00000103,V01,A00000103-V01,1,0.50,4,1.0,1.0,Yearly,...,4.0,1.0,182.0,Tourism,37330.0,1604,292.0,CL01,1.0,1389.39
14674,44801,A00000221,V01,A00000221-V01,1,0.50,4,3.0,2.0,Biannual,...,13.0,9.0,203.0,Tourism,27210.0,1342,3931.0,CL01,1.0,671.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1173,3533,A00091339,V01,A00091339-V01,1,0.50,4,27.0,1.0,Biannual,...,8.0,5.0,205.0,Tourism,27300.0,1390,NaN,NaN,0.0,0.00
29991,91160,A00091344,V01,A00091344-V01,1,0.50,4,4.0,4.0,Yearly,...,6.0,5.0,178.0,Tourism,24100.0,1365,9343.0,CL02,1.0,356.26
29990,91160,A00091344,V01,A00091344-V01,1,0.50,4,4.0,4.0,Yearly,...,6.0,5.0,178.0,Tourism,24100.0,1365,4218.0,CL01,1.0,471.93
27984,85008,A00091466,V01,A00091466-V01,1,0.50,4,25.0,2.0,Monthly,...,3.0,1.0,160.0,Tourism,12690.0,975,10849.0,CL01,1.0,856.64
27985,85008,A00091466,V01,A00091466-V01,1,0.50,4,25.0,2.0,Monthly,...,3.0,1.0,160.0,Tourism,12690.0,975,14271.0,CL02,1.0,618.00

Après analyse des doublons sur la base du numéro d'identification du client, on constate que les doublons ne sont pas forcémment les doublons car ils s'agit d'observations qui ne diffrèrent pas d'une variable à une autre sauf pour le cas de la variable "id_claim" suivant le même type du numéro d'identification du client.

### Gestion des données manquantes dans la base finale

In [ ]:
#première vérification
base_ass.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32895 entries, 0 to 32894
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0_x      32895 non-null  int64
 1   id_client         32895 non-null  object
 2   id_vehicle        32895 non-null  object
 3   id_policy         32895 non-null  object
 4   id_year           32895 non-null  int64
 5   pol_bonus         32895 non-null  float64
 6   pol_coverage      32895 non-null  int64
 7   pol_duration      32895 non-null  float64
 8   pol_sit_duration  32895 non-null  float64
 9   pol_pay_freq      32895 non-null  object
 10  pol_payd          32895 non-null  object
 11  pol_usage         32895 non-null  object
 12  pol_insee_code    32895 non-null  object
 13  drv_drv2          32895 non-null  object
 14  drv_age1          32895 non-null  float64
 15  drv_age2          32895 non-null  float64
 16  drv_sex1          32895 non-null  object
 17  drv_sex2          32895 non-null  object
 18  drv_age_lic1      32895 non-null  float64
 19  drv_age_lic2      32895 non-null  float64
 20  vh_age            32895 non-null  float64
 21  vh_cyl            32895 non-null  float64
 22  vh_din            32895 non-null  float64
 23  vh_fuel           32895 non-null  object
 24  vh_make           32895 non-null  object
 25  vh_model          32895 non-null  object
 26  vh_sale_begin     32895 non-null  float64
 27  vh_sale_end       32895 non-null  float64
 28  vh_speed          32895 non-null  float64
 29  vh_type           32895 non-null  object
 30  vh_value          32895 non-null  float64
 31  vh_weight         32895 non-null  int64
 32  Unnamed: 0_y      4968 non-null   float64
 33  id_claim          4968 non-null   object
 34  claim_nb          32895 non-null  float64
 35  claim_amount      32895 non-null  float64
dtypes: float64(17), int64(4), object(15)
memory usage: 9.0+ MB

In [ ]:
# Deuxième vérification
base_ass.isna().sum()/len(base_ass)*100

Unnamed: 0_x         0.000000
id_client            0.000000
id_vehicle           0.000000
id_policy            0.000000
id_year              0.000000
pol_bonus            0.000000
pol_coverage         0.000000
pol_duration         0.000000
pol_sit_duration     0.000000
pol_pay_freq         0.000000
pol_payd             0.000000
pol_usage            0.000000
pol_insee_code       0.000000
drv_drv2             0.000000
drv_age1             0.000000
drv_age2             0.000000
drv_sex1             0.000000
drv_sex2             0.000000
drv_age_lic1         0.000000
drv_age_lic2         0.000000
vh_age               0.000000
vh_cyl               0.000000
vh_din               0.000000
vh_fuel              0.000000
vh_make              0.000000
vh_model             0.000000
vh_sale_begin        0.000000
vh_sale_end          0.000000
vh_speed             0.000000
vh_type              0.000000
vh_value             0.000000
vh_weight            0.000000
Unnamed: 0_y        84.897401
id_claim            84.897401
claim_nb             0.000000
claim_amount         0.000000
dtype: float64

In [78]:
base_ass = base_ass.drop(columns=["Unnamed: 0_y","Unnamed: 0_x"])

base_ass.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_client         32313 non-null  object
 1   id_vehicle        32313 non-null  object
 2   id_policy         32313 non-null  object
 3   id_year           32313 non-null  int64
 4   pol_bonus         32313 non-null  float64
 5   pol_coverage      32313 non-null  int64
 6   pol_duration      32313 non-null  float64
 7   pol_sit_duration  32313 non-null  float64
 8   pol_pay_freq      32313 non-null  object
 9   pol_payd          32313 non-null  object
 10  pol_usage         32313 non-null  object
 11  pol_insee_code    32313 non-null  object
 12  drv_drv2          32313 non-null  object
 13  drv_age1          32313 non-null  float64
 14  drv_age2          32313 non-null  float64
 15  drv_sex1          32313 non-null  object
 16  drv_sex2          32313 non-null  object
 17  drv_age_lic1      32313 non-null  float64
 18  drv_age_lic2      32313 non-null  float64
 19  vh_age            32313 non-null  float64
 20  vh_cyl            32313 non-null  float64
 21  vh_din            32313 non-null  float64
 22  vh_fuel           32313 non-null  object
 23  vh_make           32313 non-null  object
 24  vh_model          32313 non-null  object
 25  vh_sale_begin     32313 non-null  float64
 26  vh_sale_end       32313 non-null  float64
 27  vh_speed          32313 non-null  float64
 28  vh_type           32313 non-null  object
 29  vh_value          32313 non-null  float64
 30  vh_weight         32313 non-null  int64
 31  nb_sin            32313 non-null  float64
 32  claim_amount      32313 non-null  float64
dtypes: float64(16), int64(3), object(14)
memory usage: 8.1+ MB

In [79]:
base_ass.to_csv("base_assures.csv")
Base_sin.to_csv("base_sinistres.csv")